DOMAIN = "hitomi.la"
TEST_CASES = [
    {
        "url": "https://hitomi.la/galleries/3953685",
        "results": [
            {
                "url": "https://hitomi.la/reader/3953685.html#1",
                "filename": "01.webp",
                "debrid_url": "NOT_NONE",
                "original_filename": "01.webp",
                "referer": "https://hitomi.la/reader/3953685.html#1",
                "album_id": "3953685",
                "uploaded_at": 1779605640,
                "download_folder": "re:Blade on Blade Out [manga] (Hitomi.la)",
            },
            {
                "url": "https://hitomi.la/reader/3953685.html#2",
                "filename": "02.webp",
                "original_filename": "02.webp",
                "referer": "https://hitomi.la/reader/3953685.html#2",
                "album_id": "3953685",
                "uploaded_at": 1779605640,
                "download_folder": "re:Blade on Blade Out [manga] (Hitomi.la)",
            },
            {
                "url": "https://hitomi.la/reader/3953685.html#3",
                "filename": "03.webp",
                "original_filename": "03.webp",
                "referer": "https://hitomi.la/reader/3953685.html#3",
                "album_id": "3953685",
                "uploaded_at": 1779605640,
                "download_folder": "re:Blade on Blade Out [manga] (Hitomi.la)",
            },
            {
                "url": "https://hitomi.la/reader/3953685.html#4",
                "filename": "04.webp",
                "original_filename": "04.webp",
                "referer": "https://hitomi.la/reader/3953685.html#4",
                "album_id": "3953685",
                "uploaded_at": 1779605640,
                "download_folder": "re:Blade on Blade Out [manga] (Hitomi.la)",
            },
            {
                "url": "https://hitomi.la/reader/3953685.html#5",
                "filename": "05.webp",
                "original_filename": "05.webp",
                "referer": "https://hitomi.la/reader/3953685.html#5",
                "album_id": "3953685",
                "uploaded_at": 1779605640,
                "download_folder": "re:Blade on Blade Out [manga] (Hitomi.la)",
            },
            {
                "url": "https://hitomi.la/reader/3953685.html#6",
                "filename": "06.webp",
                "original_filename": "06.webp",
                "referer": "https://hitomi.la/reader/3953685.html#6",
                "album_id": "3953685",
                "uploaded_at": 1779605640,
                "download_folder": "re:Blade on Blade Out [manga] (Hitomi.la)",
            },
            {
                "url": "https://hitomi.la/reader/3953685.html#7",
                "filename": "07.webp",
                "original_filename": "07.webp",
                "referer": "https://hitomi.la/reader/3953685.html#7",
                "album_id": "3953685",
                "uploaded_at": 1779605640,
                "download_folder": "re:Blade on Blade Out [manga] (Hitomi.la)",
            },
            {
                "url": "https://hitomi.la/reader/3953685.html#8",
                "filename": "08.webp",
                "original_filename": "08.webp",
                "referer": "https://hitomi.la/reader/3953685.html#8",
                "album_id": "3953685",
                "uploaded_at": 1779605640,
                "download_folder": "re:Blade on Blade Out [manga] (Hitomi.la)",
            },
            {
                "url": "https://hitomi.la/reader/3953685.html#9",
                "filename": "09.webp",
                "original_filename": "09.webp",
                "referer": "https://hitomi.la/reader/3953685.html#9",
                "album_id": "3953685",
                "uploaded_at": 1779605640,
                "download_folder": "re:Blade on Blade Out [manga] (Hitomi.la)",
            },
            {
                "url": "https://hitomi.la/reader/3953685.html#10",
                "filename": "10.webp",
                "original_filename": "10.webp",
                "referer": "https://hitomi.la/reader/3953685.html#10",
                "album_id": "3953685",
                "uploaded_at": 1779605640,
                "download_folder": "re:Blade on Blade Out [manga] (Hitomi.la)",
            },
            {
                "url": "https://hitomi.la/reader/3953685.html#11",
                "filename": "11.webp",
                "original_filename": "11.webp",
                "referer": "https://hitomi.la/reader/3953685.html#11",
                "album_id": "3953685",
                "uploaded_at": 1779605640,
                "download_folder": "re:Blade on Blade Out [manga] (Hitomi.la)",
            },
            {
                "url": "https://hitomi.la/reader/3953685.html#12",
                "filename": "12.webp",
                "original_filename": "12.webp",
                "referer": "https://hitomi.la/reader/3953685.html#12",
                "album_id": "3953685",
                "uploaded_at": 1779605640,
                "download_folder": "re:Blade on Blade Out [manga] (Hitomi.la)",
            },
            {
                "url": "https://hitomi.la/reader/3953685.html#13",
                "filename": "13.webp",
                "original_filename": "13.webp",
                "referer": "https://hitomi.la/reader/3953685.html#13",
                "album_id": "3953685",
                "uploaded_at": 1779605640,
                "download_folder": "re:Blade on Blade Out [manga] (Hitomi.la)",
            },
            {
                "url": "https://hitomi.la/reader/3953685.html#14",
                "filename": "14.webp",
                "original_filename": "14.webp",
                "referer": "https://hitomi.la/reader/3953685.html#14",
                "album_id": "3953685",
                "uploaded_at": 1779605640,
                "download_folder": "re:Blade on Blade Out [manga] (Hitomi.la)",
            },
            {
                "url": "https://hitomi.la/reader/3953685.html#15",
                "filename": "15.webp",
                "original_filename": "15.webp",
                "referer": "https://hitomi.la/reader/3953685.html#15",
                "album_id": "3953685",
                "uploaded_at": 1779605640,
                "download_folder": "re:Blade on Blade Out [manga] (Hitomi.la)",
            },
            {
                "url": "https://hitomi.la/reader/3953685.html#16",
                "filename": "16.webp",
                "original_filename": "16.webp",
                "referer": "https://hitomi.la/reader/3953685.html#16",
                "album_id": "3953685",
                "uploaded_at": 1779605640,
                "download_folder": "re:Blade on Blade Out [manga] (Hitomi.la)",
            },
            {
                "url": "https://hitomi.la/reader/3953685.html#17",
                "filename": "17.webp",
                "original_filename": "17.webp",
                "referer": "https://hitomi.la/reader/3953685.html#17",
                "album_id": "3953685",
                "uploaded_at": 1779605640,
                "download_folder": "re:Blade on Blade Out [manga] (Hitomi.la)",
            },
            {
                "url": "https://hitomi.la/reader/3953685.html#18",
                "filename": "18.webp",
                "original_filename": "18.webp",
                "referer": "https://hitomi.la/reader/3953685.html#18",
                "album_id": "3953685",
                "uploaded_at": 1779605640,
                "download_folder": "re:Blade on Blade Out [manga] (Hitomi.la)",
            },
            {
                "url": "https://hitomi.la/reader/3953685.html#19",
                "filename": "19.webp",
                "original_filename": "19.webp",
                "referer": "https://hitomi.la/reader/3953685.html#19",
                "album_id": "3953685",
                "uploaded_at": 1779605640,
                "download_folder": "re:Blade on Blade Out [manga] (Hitomi.la)",
            },
        ],
        "count": 19,
    },
    {
        "url": "https://hitomi.la/artist/tamabi-all.html",
        "results": [
            {
                "url": "ANY",
                "debrid_url": "NOT_NONE",
                "album_id": "NOT_NONE",
                "uploaded_at": int,
                "download_folder": "re:tamabi [artist][all] (Hitomi.la)/",
            },
        ],
        "count": range(13569, 15000),
    },
]
