DOMAIN = "mitaku.net"
TEST_CASES = [
    {
        "url": "https://mitaku.net/ero-cosplay/hologana-arlecchino-lingerie",
        "results": [
            {
                "url": "https://mitaku.net/wp-content/plugins/meta-slider-and-carousel-with-lightbox-pro/assets/images/spacer.gif",
                "filename": "spacer.gif",
                "debrid_url": None,
                "original_filename": "spacer.gif",
                "referer": "https://mitaku.net/ero-cosplay/hologana-arlecchino-lingerie",
                "album_id": "358679",
                "uploaded_at": 1786197600,
                "download_folder": "re:2026-08-08 - 358679 - Hologana - Arlecchino Lingerie - Mitak (Mitaku.net)",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-1.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-1.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-1.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-2.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-2.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-2.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-3.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-3.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-3.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-4.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-4.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-4.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-5.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-5.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-5.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-6.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-6.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-6.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-7.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-7.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-7.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-8.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-8.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-8.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-9.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-9.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-9.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-10.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-10.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-10.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-11.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-11.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-11.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-12.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-12.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-12.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-13.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-13.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-13.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-14.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-14.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-14.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-15.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-15.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-15.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-16.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-16.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-16.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-17.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-17.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-17.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-18.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-18.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-18.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-19.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-19.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-19.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-20.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-20.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-20.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-21.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-21.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-21.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-22.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-22.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-22.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-23.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-23.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-23.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-24.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-24.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-24.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-25.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-25.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-25.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-26.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-26.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-26.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-27.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-27.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-27.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-28.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-28.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-28.jpg",
            },
            {
                "url": "https://mitaku.net/wp-content/uploads/2026/08/Hologana-Arlecchino-Lingerie-29.jpg",
                "filename": "Hologana-Arlecchino-Lingerie-29.jpg",
                "debrid_url": None,
                "original_filename": "Hologana-Arlecchino-Lingerie-29.jpg",
            },
        ],
        "count": 30,
    }
]
