DOMAIN = "omegascans"
TEST_CASES = [
    {
        "url": "https://omegascans.org/series/moby-dick/chapter-91",
        "results": [
            {
                "url": "https://media.omegascans.org/file/zFSsXt/uploads/series/moby-dick/ddc04fbe-20ab-4ec8-8585-8fa32cf732f4/01.jpg",
                "filename": "01.jpg",
                "debrid_link": None,
                "original_filename": "01.jpg",
                "referer": "https://omegascans.org/series/moby-dick/chapter-91",
                "album_id": None,
                "uploaded_at": 1777584948,
                "download_folder": "re:Moby Dick (OmegaScans)/Chapter 91",
            },
            {
                "url": "https://media.omegascans.org/file/zFSsXt/uploads/series/moby-dick/ddc04fbe-20ab-4ec8-8585-8fa32cf732f4/02.jpg",
                "filename": "02.jpg",
                "debrid_link": None,
                "original_filename": "02.jpg",
                "referer": "https://omegascans.org/series/moby-dick/chapter-91",
                "album_id": None,
                "uploaded_at": 1777584948,
                "download_folder": "re:Moby Dick (OmegaScans)/Chapter 91",
            },
            {
                "url": "https://media.omegascans.org/file/zFSsXt/uploads/series/moby-dick/ddc04fbe-20ab-4ec8-8585-8fa32cf732f4/03.jpg",
                "filename": "03.jpg",
                "debrid_link": None,
                "original_filename": "03.jpg",
                "referer": "https://omegascans.org/series/moby-dick/chapter-91",
                "album_id": None,
                "uploaded_at": 1777584948,
                "download_folder": "re:Moby Dick (OmegaScans)/Chapter 91",
            },
            {
                "url": "https://media.omegascans.org/file/zFSsXt/uploads/series/moby-dick/ddc04fbe-20ab-4ec8-8585-8fa32cf732f4/04.jpg",
                "filename": "04.jpg",
                "debrid_link": None,
                "original_filename": "04.jpg",
                "referer": "https://omegascans.org/series/moby-dick/chapter-91",
                "album_id": None,
                "uploaded_at": 1777584948,
                "download_folder": "re:Moby Dick (OmegaScans)/Chapter 91",
            },
            {
                "url": "https://media.omegascans.org/file/zFSsXt/uploads/series/moby-dick/ddc04fbe-20ab-4ec8-8585-8fa32cf732f4/05.jpg",
                "filename": "05.jpg",
                "debrid_link": None,
                "original_filename": "05.jpg",
                "referer": "https://omegascans.org/series/moby-dick/chapter-91",
                "album_id": None,
                "uploaded_at": 1777584948,
                "download_folder": "re:Moby Dick (OmegaScans)/Chapter 91",
            },
            {
                "url": "https://media.omegascans.org/file/zFSsXt/uploads/series/moby-dick/ddc04fbe-20ab-4ec8-8585-8fa32cf732f4/06.jpg",
                "filename": "06.jpg",
                "debrid_link": None,
                "original_filename": "06.jpg",
                "referer": "https://omegascans.org/series/moby-dick/chapter-91",
                "album_id": None,
                "uploaded_at": 1777584948,
                "download_folder": "re:Moby Dick (OmegaScans)/Chapter 91",
            },
            {
                "url": "https://media.omegascans.org/file/zFSsXt/uploads/series/moby-dick/ddc04fbe-20ab-4ec8-8585-8fa32cf732f4/07.jpg",
                "filename": "07.jpg",
                "debrid_link": None,
                "original_filename": "07.jpg",
                "referer": "https://omegascans.org/series/moby-dick/chapter-91",
                "album_id": None,
                "uploaded_at": 1777584948,
                "download_folder": "re:Moby Dick (OmegaScans)/Chapter 91",
            },
            {
                "url": "https://media.omegascans.org/file/zFSsXt/uploads/series/moby-dick/ddc04fbe-20ab-4ec8-8585-8fa32cf732f4/08.jpg",
                "filename": "08.jpg",
                "debrid_link": None,
                "original_filename": "08.jpg",
                "referer": "https://omegascans.org/series/moby-dick/chapter-91",
                "album_id": None,
                "uploaded_at": 1777584948,
                "download_folder": "re:Moby Dick (OmegaScans)/Chapter 91",
            },
            {
                "url": "https://media.omegascans.org/file/zFSsXt/uploads/series/moby-dick/ddc04fbe-20ab-4ec8-8585-8fa32cf732f4/09.jpg",
                "filename": "09.jpg",
                "debrid_link": None,
                "original_filename": "09.jpg",
                "referer": "https://omegascans.org/series/moby-dick/chapter-91",
                "album_id": None,
                "uploaded_at": 1777584948,
                "download_folder": "re:Moby Dick (OmegaScans)/Chapter 91",
            },
        ],
        "count": 9,
    }
]
