DOMAIN = "whyp.it"
TEST_CASES = [
    {
        "url": "https://whyp.it/tracks/reading-your-shy-besties-mind-4eyNuDoUzLk1?token=WBPWv",
        "description": "Private track (requires the ?token param to access)",
        "results": [
            {
                "url": "re:https://cdn.whyp.it/7777d4c0-0b06-4500-89e0-f0d960b0a4a4.mp3?token",
                "filename": "Reading Your Shy Besties Mind [4eyNuDoUzLk1].mp3",
                "debrid_url": None,
                "original_filename": "Reading Your Shy Bestie's Mind",
                "referer": "https://whyp.it/tracks/reading-your-shy-besties-mind-4eyNuDoUzLk1?token=WBPWv",
                "album_id": None,
                "uploaded_at": 1777422482,
                "download_folder": "re:beegeewanders (Whyp.it)",
            }
        ],
        "count": 1,
    },
    {
        "url": "https://whyp.it/users/brad-cGgThTrh8wcG",
        "results": [
            {
                "url": "re:https://cdn.whyp.it/5e9de576-f33a-40ea-bd43-1693a568a6a0.mp3",
                "filename": "Fallout 3 Intro Remake [SLEphiH9vh0q].mp3",
                "debrid_url": None,
                "original_filename": "Fallout 3 Intro Remake",
                "referer": "https://whyp.it/tracks/fallout-3-intro-remake-SLEphiH9vh0q",
                "album_id": None,
                "uploaded_at": 1764003590,
                "download_folder": "re:Brad (Whyp.it)",
                "thumbnail": None,
            },
            {
                "url": "re:https://cdn.whyp.it/0d7a196b-3e1a-4510-a4a4-6189c56ecb27.flac",
                "filename": "Jason Waters - Heart of the Throne [QEYqRdMfoIG8].flac",
                "debrid_url": None,
                "original_filename": "Jason Waters - Heart of the Throne",
                "referer": "https://whyp.it/tracks/jason-waters-heart-of-the-throne-QEYqRdMfoIG8",
                "album_id": None,
                "uploaded_at": 1763408657,
                "download_folder": "re:Brad (Whyp.it)",
                "thumbnail": "https://cdn.whyp.it/b42b34d3-5839-4a26-9c32-41e917f31f6b.jpg",
            },
            {
                "url": "re:https://cdn.whyp.it/3d134d07-7c55-4a6b-b321-56ce90ee1fc8.flac",
                "filename": "Example Track [HPuZgly3yViP].flac",
                "debrid_url": None,
                "original_filename": "Example Track",
                "referer": "https://whyp.it/tracks/example-track-HPuZgly3yViP",
                "album_id": None,
                "uploaded_at": 1643216583,
                "download_folder": "re:Brad (Whyp.it)",
                "thumbnail": "https://cdn.whyp.it/4d6f6af1-0114-4e92-863b-996ff3a2f642.jpg",
            },
        ],
        "count": 3,
    },
    {
        "url": "https://whyp.it/collections/example-collection-hNdBmugKbF85",
        "results": [
            {
                "url": "re:https://cdn.whyp.it/3d134d07-7c55-4a6b-b321-56ce90ee1fc8.flac?token=",
                "filename": "Example Track [HPuZgly3yViP].flac",
                "debrid_url": None,
                "original_filename": "Example Track",
                "referer": "https://whyp.it/tracks/example-track-HPuZgly3yViP",
                "album_id": None,
                "uploaded_at": 1708365679,
                "download_folder": "re:Brad (Whyp.it)/Example Collection",
                "thumbnail": "https://cdn.whyp.it/4d6f6af1-0114-4e92-863b-996ff3a2f642.jpg",
            },
            {
                "url": "re:https://cdn.whyp.it/0d7a196b-3e1a-4510-a4a4-6189c56ecb27.flac?token=",
                "filename": "Jason Waters - Heart of the Throne [QEYqRdMfoIG8].flac",
                "debrid_url": None,
                "original_filename": "Jason Waters - Heart of the Throne",
                "referer": "https://whyp.it/tracks/jason-waters-heart-of-the-throne-QEYqRdMfoIG8",
                "album_id": None,
                "uploaded_at": 1763408701,
                "download_folder": "re:Brad (Whyp.it)/Example Collection",
                "thumbnail": "https://cdn.whyp.it/b42b34d3-5839-4a26-9c32-41e917f31f6b.jpg",
            },
            {
                "url": "re:https://cdn.whyp.it/5e9de576-f33a-40ea-bd43-1693a568a6a0.mp3?token=",
                "filename": "Fallout 3 Intro Remake [SLEphiH9vh0q].mp3",
                "debrid_url": None,
                "referer": "https://whyp.it/tracks/fallout-3-intro-remake-SLEphiH9vh0q",
                "album_id": None,
                "download_folder": "re:Brad (Whyp.it)/Example Collection",
                "thumbnail": None,
            },
        ],
    },
]
