DOMAIN = "yurivan"
TEST_CASES = [
    {
        "url": "https://www.yurivan.com/story/32cbf138-f76d-447f-86f2-352977b461e2/chapter/1",
        "results": [
            {
                "url": "re:/d616da37-4b88-4bdf-9106-697df8195393/playlist.m3u8",
                "filename": "Leatherman 4 — Episode 4 [hevc][mp4a][1080p].mp4",
                "debrid_url": None,
                "original_filename": "Leatherman 4 — Episode 4",
                "referer": "https://www.yurivan.com/story/32cbf138-f76d-447f-86f2-352977b461e2/chapter/1",
                "album_id": None,
                "uploaded_at": 1778058102,
                "download_folder": "re:Loose Files (Yurivan)",
            }
        ],
        "count": 1,
    },
    {
        "url": "https://www.yurivan.com/story/e5a3eecf-a920-44e9-80da-b09ace8aafb8/read?chapter=1",
        "results": [
            {
                "url": "https://img.yurivan.com/published/seed/cddf94f2-2c83-4ae4-8bfe-4622f1c4feb5/0.jpg",
                "filename": "0.jpg",
                "debrid_url": None,
                "original_filename": "0.jpg",
                "referer": "https://www.yurivan.com/story/e5a3eecf-a920-44e9-80da-b09ace8aafb8/read?chapter=1",
                "album_id": "e5a3eecf-a920-44e9-80da-b09ace8aafb8",
                "uploaded_at": None,
                "download_folder": "re:Traditional Erotic Fairy Tale (Yurivan)/Chapter 1",
            },
            {
                "url": "https://img.yurivan.com/published/seed/cddf94f2-2c83-4ae4-8bfe-4622f1c4feb5/1.jpg",
                "filename": "1.jpg",
                "debrid_url": None,
                "original_filename": "1.jpg",
                "referer": "https://www.yurivan.com/story/e5a3eecf-a920-44e9-80da-b09ace8aafb8/read?chapter=1",
                "album_id": "e5a3eecf-a920-44e9-80da-b09ace8aafb8",
                "uploaded_at": None,
                "download_folder": "re:Traditional Erotic Fairy Tale (Yurivan)/Chapter 1",
            },
            {
                "url": "https://img.yurivan.com/published/seed/cddf94f2-2c83-4ae4-8bfe-4622f1c4feb5/2.jpg",
                "filename": "2.jpg",
                "debrid_url": None,
                "original_filename": "2.jpg",
                "referer": "https://www.yurivan.com/story/e5a3eecf-a920-44e9-80da-b09ace8aafb8/read?chapter=1",
                "album_id": "e5a3eecf-a920-44e9-80da-b09ace8aafb8",
                "uploaded_at": None,
                "download_folder": "re:Traditional Erotic Fairy Tale (Yurivan)/Chapter 1",
            },
            {
                "url": "https://img.yurivan.com/published/seed/cddf94f2-2c83-4ae4-8bfe-4622f1c4feb5/3.jpg",
                "filename": "3.jpg",
                "debrid_url": None,
                "original_filename": "3.jpg",
                "referer": "https://www.yurivan.com/story/e5a3eecf-a920-44e9-80da-b09ace8aafb8/read?chapter=1",
                "album_id": "e5a3eecf-a920-44e9-80da-b09ace8aafb8",
                "uploaded_at": None,
                "download_folder": "re:Traditional Erotic Fairy Tale (Yurivan)/Chapter 1",
            },
            {
                "url": "https://img.yurivan.com/published/seed/cddf94f2-2c83-4ae4-8bfe-4622f1c4feb5/4.jpg",
                "filename": "4.jpg",
                "debrid_url": None,
                "original_filename": "4.jpg",
                "referer": "https://www.yurivan.com/story/e5a3eecf-a920-44e9-80da-b09ace8aafb8/read?chapter=1",
                "album_id": "e5a3eecf-a920-44e9-80da-b09ace8aafb8",
                "uploaded_at": None,
                "download_folder": "re:Traditional Erotic Fairy Tale (Yurivan)/Chapter 1",
            },
            {
                "url": "https://img.yurivan.com/published/seed/cddf94f2-2c83-4ae4-8bfe-4622f1c4feb5/5.jpg",
                "filename": "5.jpg",
                "debrid_url": None,
                "original_filename": "5.jpg",
                "referer": "https://www.yurivan.com/story/e5a3eecf-a920-44e9-80da-b09ace8aafb8/read?chapter=1",
                "album_id": "e5a3eecf-a920-44e9-80da-b09ace8aafb8",
                "uploaded_at": None,
                "download_folder": "re:Traditional Erotic Fairy Tale (Yurivan)/Chapter 1",
            },
        ],
        "count": 6,
    },
    {
        "url": "https://www.yurivan.com/story/e5a3eecf-a920-44e9-80da-b09ace8aafb8/read?chapter=3",
        "results": [
            {
                "url": "https://img.yurivan.com/published/seed/7ea3a059-2cdf-4866-9593-3357831ba644/0.webp",
                "filename": "0.webp",
                "debrid_url": None,
                "original_filename": "0.webp",
                "referer": "https://www.yurivan.com/story/e5a3eecf-a920-44e9-80da-b09ace8aafb8/read?chapter=3",
                "album_id": "e5a3eecf-a920-44e9-80da-b09ace8aafb8",
                "uploaded_at": None,
                "download_folder": "re:Traditional Erotic Fairy Tale (Yurivan)/Chapter 3",
            },
            {
                "url": "https://img.yurivan.com/published/seed/7ea3a059-2cdf-4866-9593-3357831ba644/1.webp",
                "filename": "1.webp",
                "debrid_url": None,
                "original_filename": "1.webp",
                "referer": "https://www.yurivan.com/story/e5a3eecf-a920-44e9-80da-b09ace8aafb8/read?chapter=3",
                "album_id": "e5a3eecf-a920-44e9-80da-b09ace8aafb8",
                "uploaded_at": None,
                "download_folder": "re:Traditional Erotic Fairy Tale (Yurivan)/Chapter 3",
            },
            {
                "url": "https://img.yurivan.com/published/seed/7ea3a059-2cdf-4866-9593-3357831ba644/2.jpg",
                "filename": "2.jpg",
                "debrid_url": None,
                "original_filename": "2.jpg",
                "referer": "https://www.yurivan.com/story/e5a3eecf-a920-44e9-80da-b09ace8aafb8/read?chapter=3",
                "album_id": "e5a3eecf-a920-44e9-80da-b09ace8aafb8",
                "uploaded_at": None,
                "download_folder": "re:Traditional Erotic Fairy Tale (Yurivan)/Chapter 3",
            },
            {
                "url": "https://img.yurivan.com/published/seed/7ea3a059-2cdf-4866-9593-3357831ba644/3.jpg",
                "filename": "3.jpg",
                "debrid_url": None,
                "original_filename": "3.jpg",
                "referer": "https://www.yurivan.com/story/e5a3eecf-a920-44e9-80da-b09ace8aafb8/read?chapter=3",
                "album_id": "e5a3eecf-a920-44e9-80da-b09ace8aafb8",
                "uploaded_at": None,
                "download_folder": "re:Traditional Erotic Fairy Tale (Yurivan)/Chapter 3",
            },
            {
                "url": "https://img.yurivan.com/published/seed/7ea3a059-2cdf-4866-9593-3357831ba644/4.jpg",
                "filename": "4.jpg",
                "debrid_url": None,
                "original_filename": "4.jpg",
                "referer": "https://www.yurivan.com/story/e5a3eecf-a920-44e9-80da-b09ace8aafb8/read?chapter=3",
                "album_id": "e5a3eecf-a920-44e9-80da-b09ace8aafb8",
                "uploaded_at": None,
                "download_folder": "re:Traditional Erotic Fairy Tale (Yurivan)/Chapter 3",
            },
            {
                "url": "https://img.yurivan.com/published/seed/7ea3a059-2cdf-4866-9593-3357831ba644/5.webp",
                "filename": "5.webp",
                "debrid_url": None,
                "original_filename": "5.webp",
                "referer": "https://www.yurivan.com/story/e5a3eecf-a920-44e9-80da-b09ace8aafb8/read?chapter=3",
                "album_id": "e5a3eecf-a920-44e9-80da-b09ace8aafb8",
                "uploaded_at": None,
                "download_folder": "re:Traditional Erotic Fairy Tale (Yurivan)/Chapter 3",
            },
            {
                "url": "https://img.yurivan.com/published/seed/7ea3a059-2cdf-4866-9593-3357831ba644/6.jpg",
                "filename": "6.jpg",
                "debrid_url": None,
                "original_filename": "6.jpg",
                "referer": "https://www.yurivan.com/story/e5a3eecf-a920-44e9-80da-b09ace8aafb8/read?chapter=3",
                "album_id": "e5a3eecf-a920-44e9-80da-b09ace8aafb8",
                "uploaded_at": None,
                "download_folder": "re:Traditional Erotic Fairy Tale (Yurivan)/Chapter 3",
            },
            {
                "url": "https://img.yurivan.com/published/seed/7ea3a059-2cdf-4866-9593-3357831ba644/7.jpg",
                "filename": "7.jpg",
                "debrid_url": None,
                "original_filename": "7.jpg",
                "referer": "https://www.yurivan.com/story/e5a3eecf-a920-44e9-80da-b09ace8aafb8/read?chapter=3",
                "album_id": "e5a3eecf-a920-44e9-80da-b09ace8aafb8",
                "uploaded_at": None,
                "download_folder": "re:Traditional Erotic Fairy Tale (Yurivan)/Chapter 3",
            },
            {
                "url": "https://img.yurivan.com/published/seed/7ea3a059-2cdf-4866-9593-3357831ba644/8.webp",
                "filename": "8.webp",
                "debrid_url": None,
                "original_filename": "8.webp",
                "referer": "https://www.yurivan.com/story/e5a3eecf-a920-44e9-80da-b09ace8aafb8/read?chapter=3",
                "album_id": "e5a3eecf-a920-44e9-80da-b09ace8aafb8",
                "uploaded_at": None,
                "download_folder": "re:Traditional Erotic Fairy Tale (Yurivan)/Chapter 3",
            },
        ],
        "count": 9,
    },
]
