from __future__ import annotations

import itertools
import time
from hashlib import sha256
from typing import TYPE_CHECKING, Any, ClassVar, Literal, NotRequired, TypedDict, TypeGuard

from cyberdrop_dl.crawlers.crawler import Crawler, RateLimit, SupportedPaths
from cyberdrop_dl.data_structures.url_objects import FILE_HOST_ALBUM, AbsoluteHttpURL, ScrapeItem
from cyberdrop_dl.exceptions import PasswordProtectedError, ScrapeError
from cyberdrop_dl.utils.utilities import error_handling_wrapper

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable

    from typing_extensions import ReadOnly


_API_ENTRYPOINT = AbsoluteHttpURL("https://api.gofile.io")
_PRIMARY_URL = AbsoluteHttpURL("https://gofile.io")


class Response(TypedDict):
    status: str


class Node(TypedDict):
    canAccess: ReadOnly[bool]
    id: str
    type: ReadOnly[Literal["folder", "file"]]
    name: str
    createTime: int


class UnlockedNode(Node):
    canAccess: Literal[True]


class File(UnlockedNode):
    type: Literal["file"]
    link: str
    directLink: NotRequired[str]  # Only present in overloaded files (imported)
    isFrozen: NotRequired[bool]  # Only present in files uploaded by free accounts and older than 30 days
    viruses: NotRequired[bool]
    md5: str

    # parentFolder: str
    # size: int
    # downloadCount: int
    # thumbnail: str


class Folder(UnlockedNode):
    type: Literal["folder"]
    code: str
    childrenCount: int
    children: dict[str, Node]
    password: NotRequired[str]
    passwordStatus: NotRequired[str]

    # isRoot: NotRequired[bool]


class GoFileCrawler(Crawler):
    SUPPORTED_PATHS: ClassVar[SupportedPaths] = {
        "Folder / File": "/d/<content_id>",
        "Direct link": (
            "/download/<content_id>/<filename>",
            "/download/web/<content_id>/<filename>",
        ),
        "**NOTE**": (
            "Use `password` as a query param to download password protected folders",
            "ex: https://gofile.io/d/ABC654?password=1234",
        ),
    }
    PRIMARY_URL: ClassVar[AbsoluteHttpURL] = _PRIMARY_URL
    DOMAIN: ClassVar[str] = "gofile"
    FOLDER_DOMAIN: ClassVar[str] = "GoFile"
    _RATE_LIMIT: ClassVar[RateLimit] = 4, 10

    _SALT: ClassVar[str] = "5d4f7g8sd45fsd"
    _BROWSER_LANG: ClassVar[str] = "en-US"

    def __post_init__(self) -> None:
        self._api_key: str = ""

    @property
    def headers(self) -> dict[str, str]:
        headers = {
            "User-Agent": (ua := self.manager.global_config.general.user_agent),
            "Origin": "https://gofile.io",
            "Referer": "https://gofile.io/",
        }
        if self._api_key:
            headers |= {
                "Authorization": f"Bearer {self._api_key}",
                "X-BL": self._BROWSER_LANG,
                "X-Website-Token": _create_web_token(
                    ua,
                    self._BROWSER_LANG,
                    self._api_key,
                    self._SALT,
                ),
            }

        return headers

    @classmethod
    def __json_resp_check__(cls, json_resp: dict[str, Any], _=None) -> None:
        if "notFound" in json_resp["status"]:
            raise ScrapeError(404)

    async def async_startup(self) -> None:
        await self._get_credentials(_API_ENTRYPOINT)

    async def fetch(self, scrape_item: ScrapeItem) -> None:
        match scrape_item.url.parts[1:]:
            case ["d", content_id]:
                return await self.folder(scrape_item, content_id)
            case ["download", "web", file_id, _]:
                return await self.single_file(scrape_item, file_id)
            case ["download", file_id, _]:
                return await self.single_file(scrape_item, file_id)
            case _:
                raise ValueError

    @error_handling_wrapper
    async def single_file(self, scrape_item: ScrapeItem, file_id: str) -> None:
        url = await self._get_redirect_url(scrape_item.url)
        scrape_item.url = url.with_fragment(file_id)
        assert "d" in url.parts
        return await self.folder(scrape_item, url.name, file_id)

    @error_handling_wrapper
    async def folder(self, scrape_item: ScrapeItem, content_id: str, single_file_id: str | None = None) -> None:
        is_first_page: bool = True

        async for folder in self._folder_pager(content_id, scrape_item.password):
            if is_first_page:
                if _has_single_not_nested_file(scrape_item, folder):
                    # Consider this file a loose file (autogenerated folder name)
                    title = ""
                    part_of_album = False
                else:
                    title = self.create_title(folder["name"], content_id)
                    part_of_album = True

                scrape_item.setup_as_album(title, album_id=content_id)
                scrape_item.part_of_album = part_of_album
                scrape_item.url = scrape_item.url.with_query(None)
                is_first_page = False

            children = folder["children"]
            if single_file_id:
                file = children.get(single_file_id)
                if not file:
                    continue

                self._handle_children(scrape_item, [file])
                return

            self._handle_children(scrape_item, children.values())

    def _handle_children(self, scrape_item: ScrapeItem, children: Iterable[Node]) -> None:
        def web_url(node: Node) -> AbsoluteHttpURL:
            node_id = node["id"]
            if node["type"] == "folder":
                return _PRIMARY_URL / "d" / (node.get("code") or node_id)
            return scrape_item.url.with_fragment(node_id)

        for node in children:
            new_scrape_item = scrape_item.create_new(web_url(node), add_parent=True)
            self._handle_node(new_scrape_item, node)
            scrape_item.add_children()

    @error_handling_wrapper
    def _handle_node(self, scrape_item: ScrapeItem, node: Node) -> None:
        if not _check_node_is_accessible(node):
            return

        coro = self.run(scrape_item) if node["type"] == "folder" else self._file(scrape_item, node)
        self.create_task(coro)

    async def _folder_pager(self, content_id: str, password: str | None = None) -> AsyncGenerator[Folder]:
        api_url = (_API_ENTRYPOINT / "contents" / content_id).with_query(
            contentFilter="",
            sortField="name",
            sortDirection=1,
            pageSize=1_000,
        )

        if password:
            sha256_password = sha256(password.encode()).hexdigest()
            api_url = api_url.update_query(password=sha256_password)

        for page in itertools.count(1):
            resp = await self.request_json(api_url.update_query(page=page), headers=self.headers)
            self.__json_resp_check__(resp)
            folder = resp["data"]
            _check_node_is_accessible(folder)
            yield folder
            if not resp["metadata"]["hasNextPage"]:
                break

    @error_handling_wrapper
    async def _file(self, scrape_item: ScrapeItem, file: File) -> None:
        link_str: str = file["link"]
        if (not link_str or link_str == "overloaded") and "directLink" in file:
            link_str = file["directLink"]

        assert link_str
        link = self.parse_url(link_str)

        if await self.check_complete_by_hash(link, "md5", file["md5"]):
            return

        if file.get("isFrozen"):
            self.log(f"{link} is marked as frozen, download may fail", 30)

        filename, ext = self.get_filename_and_ext(file["name"], mime_type=file.get("mimetype"))
        scrape_item.possible_datetime = file["createTime"]
        await self.handle_file(link, scrape_item, file["name"], ext, custom_filename=filename, metadata=file)

    @error_handling_wrapper
    async def _get_credentials(self, _) -> None:
        with self.disable_on_error("Unable to get api_key"):
            if key := self.manager.auth_config.gofile.api_key:
                self._api_key = key
            else:
                self._api_key = await self._create_temp_account()
            self.update_cookies({"accountToken": self._api_key})

    async def _create_temp_account(self) -> str:
        self.log("Creating temp Gofile account")
        api_url = _API_ENTRYPOINT / "accounts"
        json_resp = await self.request_json(api_url, method="POST", data={}, headers=self.headers)
        if json_resp["status"] != "ok":
            raise ScrapeError(401, "Couldn't generate GoFile API token", origin=api_url)

        return json_resp["data"]["token"]


def _check_node_is_accessible(node: Node) -> TypeGuard[File | Folder]:
    if (type_ := node["type"]) not in ("file", "folder"):
        raise ScrapeError(f"Unknown node type: {type_}")

    if node.get("viruses"):
        raise ScrapeError("Dangerous File")

    if node["canAccess"]:
        return True

    if node.get("password"):
        status = node.get("passwordStatus", "")
        error_msg = {
            "passwordRequired": "Folder is password protected",
            "passwordWrong": "Wrong folder password",
        }.get(status)
        raise PasswordProtectedError(error_msg)

    raise ScrapeError(403, "Folder is private")


def _has_single_not_nested_file(scrape_item: ScrapeItem, folder: Folder) -> bool:
    return folder["childrenCount"] == 1 and folder["name"] == folder["code"] and scrape_item.type != FILE_HOST_ALBUM


def _create_web_token(user_agent: str, brower_lang: str, api_key: str, salt: str) -> str:
    # "https://gofile.io/dist/js/wt.obf.js"
    # TODO: Get the salt automatically from the JS code
    token = f"{user_agent}::{brower_lang}::{api_key}::{int(time.time() // 14400)}::{salt}"
    return sha256(token.encode()).hexdigest()
