name: Ruff

permissions: {}

on:
  push:
  pull_request:

jobs:
  ruff:
    name: Lint and format
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - uses: astral-sh/ruff-action@v4.0.0
      - run: ruff format --check --diff
        if: ${{ !cancelled() }}
